name: Maven Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Maven Repository
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: softpostbox-jar
          path: target/*.jar
